### ISSUE TITLE
Properties frameworks are not correct

### ISSUE THREAD

**Issue by bilalshaikh42** [biosimulators/Biosimulators_VCell#22]
The model framework is set to SBO_0000293 (non spatial continuous), even for the algorithms that seem to use spatial methods.

**Comment by jonrkarr** [comment]
@gmarupilla created this. I haven't reviewed this yet. There's a few issues with the metadata.

These algorithms should be changed to spatial continuous framework:
- finite volume method (KISAO_0000285)
- finite volume method (KISAO_0000285)
- Brownian diffusion Smoluchowski method (KISAO_0000057)

It seems that new terms need to be added to KISAO to capture all of the algorithms. Currently, there aren't sufficiently specific terms. As a result, multiple algorithms are getting mapped to the same KISAO terms.
