### ISSUE TITLE
Parameters have incorrect Kisao Ids

### ISSUE THREAD

**Issue by bilalshaikh42** [biosimulators/Biosimulators_VCell#24]
For various algorithms, It seems that the kisao ids of the parameters are set to the same one as the algorithm

**Comment by jonrkarr** [comment]
The parameters are not correctly annotated. It looks like the parameters have been copied for each algorithm.

The parameters of each algorithm need to be annotated using KiSAO:

- [ ] Determine the parameters of each algorithm
    - Id/name within VCell
    - type: integer, float, boolean
    - default value
- [ ] Find the KiSAO term for each parameter: use OLS to browse the available terms: https://www.ebi.ac.uk/ols/ontologies/kisao
   - If necessary, request new KiSAO terms: https://sourceforge.net/p/kisao/feature-requests/

**Comment by gmarupilla** [comment]
Yes, some of them were wrong and @vcellmike is working on rewriting them.

**Comment by jonrkarr** [comment]
This is partly fixed. Although the annotation is complete. This issue is superseded by #45.
