### ISSUE TITLE
Provide more informative error messages

### ISSUE THREAD

**Issue by jonrkarr** [biosimulators/Biosimulators_VCell#39]
Below is an example of a less than informative message. The message also has a typo: "combingation".

```
/home/FCAM/crbmapi/nfs/biosimulations/simulations/5fd38d56105d25791b5990b1/in/BIOMD0000000297.omex' saved [11454/11454]

Exception in thread "main" java.lang.IllegalArgumentException: Invalid level/version combingation - must be 1-1 or 1-2 but was 1,3
	at org.jlibsedml.validation.SchemaValidatorImpl.getSchema(SchemaValidatorImpl.java:94)
	at org.jlibsedml.validation.SchemaValidatorImpl.validateSedMLString(SchemaValidatorImpl.java:48)
	at org.jlibsedml.validation.RawContentsSchemaValidator.validate(RawContentsSchemaValidator.java:24)
	at org.jlibsedml.Libsedml.readDocumentFromString(Libsedml.java:344)
	at org.jlibsedml.Libsedml.readDocument(Libsedml.java:92)
	at org.vcell.cli.CLIStandalone.main(CLIStandalone.java:41)
```

**Comment by jonrkarr** [comment]
Below is an example of an even less informative error message. In this case, VCell provides no information about the error. Note, tellurium and GillesPy2 both correctly simulate this archive. If we cannot resolve this issues quickly, we will need to remove remove VCell from runBioSimulations until this is corrected. A journal editor needs to be able to quickly verify that runBioSimulations works.

[BIOMD0000000297.edited-ssa.omex.zip](https://github.com/biosimulators/Biosimulators_VCell/files/5681987/BIOMD0000000297.edited-ssa.omex.zip)

```
/home/FCAM/crbmapi/nfs/biosimulations/simulations/5fd3fa44105d25259a59912b/in/BIOMD0000000297.edited-ssa.omex' saved [18735/18735]

java.lang.NullPointerException
	at cbit.vcell.xml.XmlHelper.sedmlToBioModel(XmlHelper.java:657)
	at org.vcell.cli.SolverHandler.simulateTask(SolverHandler.java:47)
	at org.vcell.cli.CLIStandalone.main(CLIStandalone.java:55)
Unable to Parse SEDML into biomodel, failed with err: Unable to initialize bioModel for the given selection.
Exception in thread "main" java.lang.RuntimeException: Imported VCDocument is null.
	at org.vcell.cli.SolverHandler.sanityCheck(SolverHandler.java:24)
	at org.vcell.cli.SolverHandler.simulateTask(SolverHandler.java:51)
	at org.vcell.cli.CLIStandalone.main(CLIStandalone.java:55)
```

**Comment by moraru** [comment]
Where is a list of all the omex files to check against errors so they run correctly with VCell

**Comment by jonrkarr** [comment]
We only have a few so far organized here:
https://github.com/biosimulators/Biosimulators_test_suite/tree/dev/biosimulators_test_suite

**Comment by gmarupilla** [comment]
[COPASI_omexes.zip](https://github.com/biosimulators/Biosimulators_VCell/files/5682109/COPASI_omexes.zip)
[VCell_omexes.zip](https://github.com/biosimulators/Biosimulators_VCell/files/5682111/VCell_omexes.zip)
OMEX archives for 827 Biomodels which has a small time interval of 10 seconds with 101 time-points.

**Comment by jonrkarr** [comment]
Keep in mind that these are automatically created OMEX files. As a result, they have low coverage of SED-ML features. These tests are mainly useful for testing different models rather than support for SED-ML. Passing these files is not an adequate test of SED-ML support. 

Below are SED-ML files constructed from BioModels, with the original errors in the SED-ML files removed. This has better coverage of SED-ML features than your examples. The tellurium images passes the great majority of these files. Keep in mind that this still has low coverage of SED-ML features (e.g., no ChangeXml, AddXml, RemoveXml, RepeatedTask, OneStep, 3D plots, only a couple of algorithms, no algorithm parameters, etc.).

[BioModels COMBINE archives.zip](https://github.com/biosimulators/Biosimulators_VCell/files/5682134/BioModels.COMBINE.archives.zip)

For the above reasons, we need to create our own test suite. This is on my todo list, but I haven't had time yet.

**Comment by jonrkarr** [comment]
In addition to the above comments, these test files do no help check that VCell's SED-ML error messages will be understandable by users.

**Comment by moraru** [comment]
I have sent this around several times, starting a long time ago, but have been ignored…  So here it is again.

This OMEX file exercises most of the critical features for any of the COMBINE archive exchange format and implementing platforms to be actually useful:

  *   A single SED-ML
  *   Two referenced SBML models
  *   20 different tasks, including repeated task construct for parameter scans
  *   Multiple algorithms (deterministic fixed timestep and variable timestep, stochastic, hybrid, and spatial)
  *   Algorithm parameters (two simulations are copies of other two simulations using the same algorithms but different tolerance parameters where two of them are expected to succeed and two of them are expected to fail on purpose because tolerance is too big)

This is actually a “real life” example of a model used for several years during the Cold Spring Harbor Laboratory summer course in computational biology.

As far as I know, there is not a single tool out there that can handle it properly, and most can’t deal with even a small subset of it.  Of course, the irony is that it is actually exported out of VCell (it is *not* a manual construct) and the latest VCell can’t handle a good chunk of it either 😊 (unless we punt to the VCML file included in the archive).

Ion

**Comment by jonrkarr** [comment]
Thanks for sharing this example. Maybe you mentioned this to Akhil, but this hasn't been shared previously.

**Comment by gmarupilla** [comment]
With the latest commit 2bc95754caf9cc52bd3be1bdaea76cf8bd0aedba, the exception messages are gone (as far as I tested with different OMEX shared by both @jonrkarr  and @moraru). 

Let me know if the result still doesn't suffice the requirement.

PS: This is the omex that @moraru shared: [CSHL_2012_Exercise_7___OMEX_test.omex
](https://github.com/biosimulators/Biosimulators_VCell/blob/dev/tests/fixtures/CSHL_2012_Exercise_7___OMEX_test.omex)

**Comment by moraru** [comment]
I have reviewed the test OMEX files provided by @jonrkarr.  Unsurprisingly, the SBML models in all 3 fail units validation (there are very few public models that don't).

Import in COPASI and VCell produce numerically consistent results as shown by attached sample plots.

I have found the following errors:
- COPASI ignores the requested algorithms and simulates everything with LSODA
- VCell correctly uses the requested algorithms (CVODEx2 and RK2 in the examples) but ignores the algorithm parameters (model 297 specifies absolute and relative tolerances) - this is a known limitation: we currently export algorithm parameters but do not yet import them; I will fix this

![297-1](https://user-images.githubusercontent.com/7397814/101992880-47082d80-3c84-11eb-8287-bcf525a743af.PNG)
![734-1](https://user-images.githubusercontent.com/7397814/101992881-496a8780-3c84-11eb-8786-9cc73b980994.PNG)
![823-8](https://user-images.githubusercontent.com/7397814/101992883-4b344b00-3c84-11eb-8e82-dbe75948fab4.PNG)

**Comment by moraru** [comment]
> With the latest commit [2bc9575](https://github.com/biosimulators/Biosimulators_VCell/commit/2bc95754caf9cc52bd3be1bdaea76cf8bd0aedba), the exception messages are gone (as far as I tested with different OMEX shared by both @jonrkarr and @moraru).
> 
> Let me know if the result still doesn't suffice the requirement.
> 
> PS: This is the omex that @moraru shared: [CSHL_2012_Exercise_7___OMEX_test.omex ](https://github.com/biosimulators/Biosimulators_VCell/blob/dev/tests/fixtures/CSHL_2012_Exercise_7___OMEX_test.omex)

@gmarupilla is your latest code executing all 8 tasks specified in OMEX 823?

**Comment by jonrkarr** [comment]
Ultimately, our goal is for (nearly all) containers to support (nearly all) SBML and SED-ML files. I think its reasonable to except that peer reviewers (who will be members of our field) will try a few of their "favorite" OMEX archives, which may be complex examples.

But, we should keep in mind that the 12/20 review is superficial. For this stage of review, we just need to be able to steer the editor (who likely isn't familiar with OMEX, SED-ML, SBML, etc.) to some working examples (which we have engineered). Specifically, next to the submission form, we need a link that takes the editor to a few working examples. Since we don't have a lot of time, we should focus on hitting this bar.

For the paper submission deadline (Jan 31), we will need the containers to have more complete OMEX/SED-ML/SBML support because the reviewers will scrutinize our work more carefully. Being more knowledgeable, the peer reviewers will also likely be more forgiving about runBioSimulations not supporting every SBML feature for every container. Peer reviewers will understand why 100% support is an unreasonable expectation.

**Comment by moraru** [comment]
My understanding is that https://github.com/biosimulators/Biosimulators_test_suite/tree/dev/biosimulators_test_suite is the collection place for the working examples to be made public on 12/20.  Is this correct?  There are currently only 3 archives there.

**Comment by gmarupilla** [comment]
> > With the latest commit [2bc9575](https://github.com/biosimulators/Biosimulators_VCell/commit/2bc95754caf9cc52bd3be1bdaea76cf8bd0aedba), the exception messages are gone (as far as I tested with different OMEX shared by both @jonrkarr and @moraru).
> > Let me know if the result still doesn't suffice the requirement.
> > PS: This is the omex that @moraru shared: [CSHL_2012_Exercise_7___OMEX_test.omex ](https://github.com/biosimulators/Biosimulators_VCell/blob/dev/tests/fixtures/CSHL_2012_Exercise_7___OMEX_test.omex)
> 
> @gmarupilla is your latest code executing all 8 tasks specified in OMEX 823?

Yes, I also made another commit to get the number of tried and failed reports correctly. Here is the archive containing the results after the simulation.
[823_result.zip](https://github.com/biosimulators/Biosimulators_VCell/files/5683644/823_result.zip)

**Comment by jonrkarr** [comment]
Yes, we can put the examples we want to steer the editor to https://github.com/biosimulators/Biosimulators_test_suite/tree/dev/biosimulators_test_suite. We can change the contents of that link as needed.

**Comment by moraru** [comment]
@jonrkarr if you already have some more examples that you intend to use please put them out there :) I'll add a couple myself (not as complex as that roundtrip test, but with cool data) after I am done dealing with jlibsedml nonsense (we have a problem as it does not support version 3)

**Comment by moraru** [comment]
> > > With the latest commit [2bc9575](https://github.com/biosimulators/Biosimulators_VCell/commit/2bc95754caf9cc52bd3be1bdaea76cf8bd0aedba), the exception messages are gone (as far as I tested with different OMEX shared by both @jonrkarr and @moraru).
> > > Let me know if the result still doesn't suffice the requirement.
> > > PS: This is the omex that @moraru shared: [CSHL_2012_Exercise_7___OMEX_test.omex ](https://github.com/biosimulators/Biosimulators_VCell/blob/dev/tests/fixtures/CSHL_2012_Exercise_7___OMEX_test.omex)
> > 
> > 
> > @gmarupilla is your latest code executing all 8 tasks specified in OMEX 823?
> 
> Yes, I also made another commit to get the number of tried and failed reports correctly. Here is the archive containing the results after the simulation.
> [823_result.zip](https://github.com/biosimulators/Biosimulators_VCell/files/5683644/823_result.zip)

@gmarupilla you cannot simply set the output spec on a solver task description without checking whether it is supported (see  cbit.vcell.solver.SolverDescription.supports(OutputTimeSpec outputTimeSpec)); the 3 RK solvers as well as FE and AM solvers only support cbit.vcell.solver.DefaultOutputTimeSpec, if you set a cbit.vcell.solver.UniformOutputTimeSpec on them you will get as an output a single data point (as you can see in the zip archive you attached); what you need to do is to take the bounds from the UniformOutputTimeSpec and use in a DefaultOutputTimeSpec that you set on the solver, and after you retrieve the dataset you convert it into the required time points by interpolation from the full solver output

**Comment by bilalshaikh42** [comment]
Just an FYI, the current vcell image is not able to load the omex file provided above.  It does however provide a friendly message. 
https://run.biosimulations.org/simulations/5fd92f0e7efd18652bc90a44#log

**Comment by gmarupilla** [comment]
The omex file got corrupted while downloading because I tried unzipping on HPC, not a zip archive.
![image](https://user-images.githubusercontent.com/53095348/102277476-59899d80-3ef6-11eb-84cc-460130e4a7c4.png)

**Comment by moraru** [comment]
> Keep in mind that these are automatically created OMEX files. As a result, they have low coverage of SED-ML features. These tests are mainly useful for testing different models rather than support for SED-ML. Passing these files is not an adequate test of SED-ML support.
> 
> Below are SED-ML files constructed from BioModels, with the original errors in the SED-ML files removed. This has better coverage of SED-ML features than your examples. The tellurium images passes the great majority of these files. Keep in mind that this still has low coverage of SED-ML features (e.g., no ChangeXml, AddXml, RemoveXml, RepeatedTask, OneStep, 3D plots, only a couple of algorithms, no algorithm parameters, etc.).
> 
> [BioModels COMBINE archives.zip](https://github.com/biosimulators/Biosimulators_VCell/files/5682134/BioModels.COMBINE.archives.zip)
> 
> For the above reasons, we need to create our own test suite. This is on my todo list, but I haven't had time yet.

OMEX 802 asks for a very large output (9,999,999 time points) which makes no sense for a 10 sec simulation.  Is this by design or a typo?

**Comment by jonrkarr** [comment]
If you're referring to a OMEX derived from BioModels, this is just copied from BioModels. Clearly another error.

**Comment by moraru** [comment]
Yes, from the zip file you uploaded here.  VCell did run it according to specs and produced a 1.2 GB csv file...
I'll edit it to ask for 1000 timepoints for further test runs.

**Comment by moraru** [comment]
On the preliminary test run out of my debugger VCell CLI ran succesfully 225 out of 252.  I suspect the 27 failures are due to SBML incompatibilities, and not to the SED-ML/OMEX import and handling.  I'll take a closer look once I am done with the code updates later tonight.

**Comment by gmarupilla** [comment]
Validated and passed, more informative error are printed out
