### ISSUE TITLE
Align SED-ML implementation with other simulation tools

### ISSUE THREAD

**Issue by jonrkarr** [biosimulators/Biosimulators_VCell#44]
- [x] Issue warning when alternative algorithm is used
- [x] Support reports (`sedml:report`)
- [x] Datasets of reports should be saved as rows rather than columns. This is motivated by multiple things including better performance for data retrieval.
- [x] Save reports to `path/to/simulation.sedml/{report-id}`. Currently, VCell does not include (`.sedml`). This extension is necessary to ensure that each report has a unique id (tuple of location of SED-ML file and report id)
- [x] Support HDF output of reports
- [x] Pass [BioSimulators test suite](https://github.com/biosimulators/biosimulators_test_suite)

**Comment by gmarupilla** [comment]
Passed and validated
