### ISSUE TITLE
Stop pushing Docker images to top-level GHCR namespace

### ISSUE THREAD

**Issue by jonrkarr** [biosimulators/Biosimulators_VCell#47]
Once VCell is able to pass the [BioSimulators test suite](https://github.com/biosimulators/biosimulators_test_suite):
- [x] The CD workflow should only push images to `ghcr.io/biosimulators/biosimulators_vcell/vcell`
- [x] The CD workflow should not directly push images to `ghcr.io/biosimulators/vcell` -- the test suite will do this if it deems the image is valid

**Comment by gmarupilla** [comment]
Passed and validated
