### ISSUE TITLE
Submit VCell 7.3.0.11

### ISSUE THREAD

**Issue by biosimulators-daemon** [biosimulators/Biosimulators_VCell#53]
---
id: vcell
version: 7.3.0.11
specificationsUrl: https://raw.githubusercontent.com/biosimulators/Biosimulators_VCell/00d08a031a0788435b44989e73ae3f43f33e4cb0/biosimulators.json
specificationsPatch:
  version: 7.3.0.11
  image:
    url: ghcr.io/biosimulators/biosimulators_vcell/vcell:7.3.0.11
validateImage: true
commitSimulator: true

---

**Comment by gmarupilla** [comment]
Validated
