### ISSUE TITLE
Command line interface doesn't support several documented arguments

### ISSUE THREAD

**Issue by jonrkarr** [biosimulators/Biosimulators_VCell#67]
The Command line interface says that it supports these arguments when it in fact does not
- `-h`, `--help`
- `-v`, `--version`

These should be implemented or removed from the inline documentation.

**Comment by gmarupilla** [comment]
I realized now, and I'll fix it. Functionality is broken due to the support of the conversion of VCML to the OMEX archive. In fact, the [last version](https://github.com/orgs/virtualcell/packages/container/vcell-cli/1483149) supports the interface(`-h`, `-v`). I'll fix it in the next commit.

**Comment by gmarupilla** [comment]
Fixed
