### ISSUE TITLE
Why does the VCell CLI dynamically try to install pip packages?

### ISSUE THREAD

**Issue by jonrkarr** [biosimulators/Biosimulators_VCell#68]
Try to help debug VCell. All dependencies can be installed into the Docker image. This is somewhat important for versioning. Why is VCell trying to install pip packages during the execution of each OMEX archive?

**Comment by gmarupilla** [comment]
It is a debug code that I can remove the statement that is not required for the docker run, but I developed the code to check the dev(local) machine's pip packages availability. I'll disable it in the next commit.

**Comment by gmarupilla** [comment]
Handled by installing VCell-cli-utils package
